### PR TITLE
Autodetect bots invite url

### PR DESCRIPTION
**Pull request by niansa**
Added new setting forced_inviteurl:
If it is set to False, the bot will automatically generate a matching bot invite URL,
if it is set to any string, that string will be used as bot invite URL.

### CODE REVIEW

**Comment by niansa** [comment]
"niansa and others" 🤔
GitHub is weird sometimes xD

**Comment by merlinfuchs** [comment]
I made some changes to keep the code consistent. That doesn't mean that your changes were bad, but I like to keep everything as clean as possible.
Thanks for your pull request :)

**Comment by niansa** [comment]
@Merlintor your configuration option invite_url won't ever apply

**Comment by merlinfuchs** [comment]
Why? 🤔

**Comment by niansa** [comment]
Nevermind, didn't see your changes in bot.py

**Comment by merlinfuchs** [comment]
👌

**Pull request merged**
